name: Release Pipeline

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
      release:
        description: 'Release the version (true/false)'
        required: true
        type: boolean
        default: false

jobs:
  check-version:
    name: Check Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: Check version format
        run: |
          if [[ ! "${{ github.event.inputs.version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Version must be in the format X.Y.Z"
            exit 1
          fi

          NEW_VERSION="${{ github.event.inputs.version }}"
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null)

          echo "Latest Git Tag: $LATEST_TAG"
          echo "New Version:    $NEW_VERSION"

          if [ "$LATEST_TAG" == "$NEW_VERSION" ]; then
              echo "Error: The new version is already live."
              exit 1
          elif [ "$(printf '%s\n' "$LATEST_TAG" "$NEW_VERSION" | sort -V | tail -n1)" == "$NEW_VERSION" ]; then
              echo "$NEW_VERSION is newer than $LATEST_TAG."
          else
              echo "Error: $NEW_VERSION is older than $LATEST_TAG."
              exit 1
          fi


  call-frontend-workflow:
    name: Build Frontend
    needs: check-version
    uses: ./.github/workflows/frontend.yml

  call-backend-workflow:
    name: Build Backend
    needs: check-version
    uses: ./.github/workflows/backend.yml


  integration-tests:
    name: Run Integration Tests
    needs: [call-frontend-workflow, call-backend-workflow]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v9.0.0
        with:
          python-version: 3.12

      - name: Docker Compose Up
        run: docker compose -f workflow-docker-compose.yml up --build -d --wait

      - name: Run Integration Tests
        working-directory: e2e
        run: |
          uv sync
          uv run playwright install chromium
          uv run playwright install-deps chromium
          uv run pytest

  build-docker-image:
    name: Build (${{ matrix.image_name }})
    needs: integration-tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true 
      matrix:
        include:
          - image_name: motorshop_frontend
            context_dir: .
            dockerfile_path: ./infra/Dockerfile/frontend/Dockerfile
          - image_name: motorshop_backend
            context_dir: .
            dockerfile_path: ./infra/Dockerfile/service/Dockerfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and export to local tarball
        uses: docker/build-push-action@v7
        with:
          context: ${{ matrix.context_dir }}
          file: ${{ matrix.dockerfile_path }}
          outputs: type=docker,dest=/tmp/${{ matrix.image_name }}.tar
          tags: ${{ matrix.image_name }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.image_name }}-artifact
          path: /tmp/${{ matrix.image_name }}.tar
          retention-days: 1

  push-docker-images:
    name: Push Docker Images to GHCR
    needs: build-docker-image
    if: ${{ github.event.inputs.release == 'true' }}

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        image_name: [motorshop_frontend, motorshop_backend]

    env:
      REGISTRY: ghcr.io

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: ${{ matrix.image_name }}-artifact
          path: /tmp
      
      - name: Load Docker image
        run: |
          docker load --input /tmp/${{ matrix.image_name }}.tar

      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.image_name }}
          tags: |
            type=raw,value=${{ github.event.inputs.version }},enable=${{ github.event.inputs.version != '' }}
            type=sha,format=short
            type=raw,value=latest,enable=${{ github.event_name == 'workflow_dispatch' }}

      - name: Tag and Push Image to GHCR
        run: |

          TAGS="${{ steps.meta.outputs.tags }}"

          for TAG in $TAGS; do
            echo "Tagging ${{ matrix.image_name }}:latest as $TAG"
            docker tag ${{ matrix.image_name }}:latest $TAG
            docker push $TAG
          done


  publish-tag:
    name: Publish Release
    needs: push-docker-images
    if: ${{ github.event.inputs.release == 'true' }}

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.event.inputs.version }} \
            --repo "$GITHUB_REPOSITORY" \
            --title "${{ github.event.inputs.version }}" \
            --generate-notes